### ISSUE TITLE
TAMPI is intercepting FFTW MPI calls

### ISSUE THREAD

**Issue by rodarima** [rodarima/cpic#14]
```
(gdb) bt
#0  0x00007f92ea4accf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007f92ea17eea1 in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:865
#2  std::condition_variable::wait (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007f92e9da3efc in TaskBlocking::taskBlocks(WorkerThread*, Task*, ThreadManagerPolicy::thread_run_inline_policy_t) ()
   from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#4  0x00007f92e9d99774 in nanos6_block_current_task () from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#5  0x00007f92ea4c9b89 in nanos6_block_current_task (blocking_context=0x7f92601b24d0) at loader/indirect-symbols/blocking.c:34
#6  0x00007f92eada3f29 in MPI_Sendrecv () from /usr/lib/libtampi-c.so.0
#7  0x00007f92eaaf9d5d in ?? () from /usr/lib/libfftw3_mpi.so.3
#8  0x00007f92eaaf9ddf in ?? () from /usr/lib/libfftw3_mpi.so.3
#9  0x00007f92eaafd6e3 in ?? () from /usr/lib/libfftw3_mpi.so.3
#10 0x00007f92eaaffe76 in ?? () from /usr/lib/libfftw3_mpi.so.3
#11 0x000000000041c4b6 in MFT_solve (sim=0x7f92601526d0, s=0x7f9260153e40, x=0x7f9260154030, b=0x7f926010c340) at src/solver.c:468
#12 0x000000000041c0ed in solve_xy (sim=0x7f92601526d0, s=0x7f9260153e40, phi=0x7f9260154030, rho=0x7f926010c340) at src/solver.c:592
#13 0x000000000040adda in field_phi_solve (sim=0x7f92601526d0) at src/field.c:439
#14 0x000000000040b876 in nanos6_unpacked_task_region_stage_field_E1 ()
#15 0x000000000040b8ac in nanos6_ol_task_region_stage_field_E1 ()
#16 0x00007f92e9da611e in ExecutionWorkflow::executeTask(Task*, ComputePlace*, MemoryPlace*) ()
   from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#17 0x00007f92e9d834b8 in WorkerThread::handleTask(CPU*) () from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#18 0x00007f92e9d83c1b in WorkerThread::body() () from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#19 0x00007f92e9d79c91 in kernel_level_thread_body_wrapper(void*) () from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#20 0x00007f92ea4a646f in start_thread () from /usr/lib/libpthread.so.0
#21 0x00007f92ea3d63d3 in clone () from /usr/lib/libc.so.6

```

**Comment by rodarima** [comment]
The performance doesn't seem to be impacted with TAMPI in the FFTW. Using the static version only intercepts calls inside our program.
