### ISSUE TITLE
Segfault with 2 processes

### ISSUE THREAD

**Issue by rodarima** [rodarima/cpic#9]
```
$ mpirun -n 2 ./cpic conf/simd.conf
...
No output path specified, output will not be saved
begin sim_pre_step
begin sim_pre_step
[xeon07:1832490] *** Process received signal ***
[xeon07:1832490] Signal: Segmentation fault (11)
[xeon07:1832490] Signal code: Address not mapped (1)
[xeon07:1832490] Failing at address: 0x7f5a62a00000
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node xeon07 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```
Now the journey begins on how to attach a GDB before OpenMPI kills my process.

**Comment by rodarima** [comment]
These did the trick:
```
$ sudo sysctl kernel.core_pattern=core.%p
$ ulimit -c unlimited
```
So we are accessing a bad block (free'd?)
```
(gdb) bt
#0  0x00000000004155ff in plist_grow (l=0x7f725814f080, n=1024) at src/plist.c:236
#1  0x0000000000407e13 in recv_plist_y (sim=0x7f7258147240, l=0x7f725814f080, dst=1, ic=11) at src/comm_plasma.c:953
#2  0x000000000040788e in recv_pchunk_y (sim=0x7f7258147240, c=0x7f725814e240) at src/comm_plasma.c:1002
#3  0x0000000000408518 in nanos6_unpacked_task_region_exchange_plasma_y1 ()
#4  0x000000000040854c in nanos6_ol_task_region_exchange_plasma_y1 ()
#5  0x00007f726430e11e in ExecutionWorkflow::executeTask(Task*, ComputePlace*, MemoryPlace*) ()
   from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#6  0x00007f72642eb4b8 in WorkerThread::handleTask(CPU*) () from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#7  0x00007f72642ebc1b in WorkerThread::body() () from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#8  0x00007f726430bcd1 in kernel_level_thread_body_wrapper(void*) () from /usr/lib/libnanos6-optimized-linear-regions-fragmented.so
#9  0x00007f7264a0e46f in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007f726493e3d3 in clone () from /usr/lib/libc.so.6
(gdb) l
231             nmax = l->nmax;
232             b = pblock_last(l->b);
233
234             if(b)
235             {
236                     if(b->n + n <= nmax)
237                     {
238                             /* No need to add another pblock */
239                             pblock_update_n(b, b->n + n);
240                             goto end;
(gdb) p b   
$4 = (pblock_t *) 0x7f9375600000
(gdb) p b->n
Cannot access memory at address 0x7f9375600000
```

**Comment by rodarima** [comment]
With valgrind, we have another bug, potentially earlier:
```
(gdb) bt
#0  0x00000000051b9ce5 in raise () from /usr/lib/libc.so.6
#1  0x00000000051a3857 in abort () from /usr/lib/libc.so.6
#2  0x00000000051a3727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00000000051b2426 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000000000407e51 in recv_plist_y (sim=0x9fff760, l=0xa108c40, dst=1, ic=0) at src/comm_plasma.c:957
#5  0x000000000040788e in recv_pchunk_y (sim=0x9fff760, c=0xa106f80) at src/comm_plasma.c:1006
#6  0x0000000000408518 in nanos6_unpacked_deps_exchange_plasma_y0 ()
#7  0x0000000007584a90 in ?? ()
#8  0x0000000000000000 in ?? ()
(gdb) l
952
953                     /* Allocate another block if needed */
954                     if(more)
955                     {
956                             dbg("Allocating another block for recv\n");
957                             plist_grow(l, l->nmax);
958                             assert(b->next == l->b->prev);
959                     }
960             }
961
(gdb) p b->next
$1 = (struct pblock *) 0x0
(gdb) p l->b->prev
$2 = (struct pblock *) 0x11a00000
(gdb) p l->b      
$3 = (struct pblock *) 0xb200000
(gdb) p l->b->next
$4 = (struct pblock *) 0x0
```

Looks like the next and prev pointers are not properly updated.
